### ISSUE TITLE
Can't search by token in admin

### ISSUE THREAD

**Issue by djm** [yunojuno/django-request-token#59]
Seeing `?rt=<token>` is the most common way issues will be reported.

And yet there is no easy way to go from <token> to finding the actual `RequestToken` in the admin.

We should improve support for this.

**Comment by hugorodgerbrown** [comment]
Took a look at this to work out why the token isn't stored on the object itself (which is the obvious solution). It's because the id of the object is encoded into the token, and that is only available post-save. So you'd have to save the object initially to get an id, then set the token on the model, then save again. This only applies to the initial creation (as once it's saved for the first time it will always have an id).

If you only ever create objects using `create_token` then updating that method to do a double save would work, but it would many any 'raw' RequestToken creation would fail. Breaking change.

**Comment by djm** [comment]
Indeed! I was wondering about this flow instead:

* user dumps token in search box
* we notice it's a JWT
* we decode it to find out the ID
* we redirect to the change page in admin for that ID

Then we don't have to mess around with creation/schema changes.

I _believe_ this can be accomplished by overriding [`ModelAdmin.get_search_results`](https://docs.djangoproject.com/en/4.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_search_results) but have somehow never used it in anger.

**Comment by hugorodgerbrown** [comment]
Had to take the day off today, so fixed this in #60.
